name: Testing PyTorch nightly

on: push # yamllint disable-line rule:truthy

jobs:

  latest_pytest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 40

      # Skip workflow if only certain files have been changed.
    - name: Get changed files
      id: changed-files-specific
      uses: tj-actions/changed-files@v34
      with:
        files: |
          benchmark/**
          conda/**
          docker/**
          docs/**
          examples/**
          graphgym/**
          README.md
          CHANGELOG.md

    - name: Setup packages
      if: steps.changed-files-specific.outputs.only_changed != 'true'
      uses: ./.github/actions/setup
      with:
        torch-version: nightly

    - name: Install main package
      if: steps.changed-files-specific.outputs.only_changed != 'true'
      run: |
        pip install -e .[test]

    - name: Run tests
      if: steps.changed-files-specific.outputs.only_changed != 'true'
      timeout-minutes: 10
      run: |
        pytest

env:
  PIP_INDEX_URL: https://pypi-wayback-449168051873.europe-west3.run.app/2023-11-15
  UV_INDEX_URL: https://pypi-wayback-449168051873.europe-west3.run.app/2023-11-15
